services:
  web:
    build: .
    command: sh -c
      "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      python manage.py create_superuser_from_env && \
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${WEBSITE_PORT}:8000"
    volumes:
      - app:/app
    environment:
      DATABASE_ENGINE: "django.db.backends.postgresql_psycopg2"
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

volumes:
  db:
  app:
